version: '3.6'
services:
  #listens on 8000
  #PROXY: true makes to so topicsUI proxies kafka-rest calls so we don't have to expose kafka rest to network
  topics-ui:
    image: ${DOCKER_IMAGE:-landoop/kafka-topics-ui:0.9.4}
    ports:
      - "8000:8000"
    networks:
      kafkarestnet:
    environment:
      KAFKA_REST_PROXY_URL: http://kafkarest:8082
      PROXY: "true"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-uidmz == true

networks:
  kafkarestnet:
    external: true
    name: kafkarest_kafkarestnet