version: '3.7'
services:

  # Listens for gelf messages on TCP
  gelflistener:
    image: <FIXME>/logstash:latest
    ports:
      - "12201:12201/tcp"
    networks:
      kafka_kafkanet:
    configs:
      - source: logstash_config
        target: /etc/logstash.conf
        uid: '33'
        gid: '33'
        mode: 0755
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

configs:
  logstash_config:
    file: ./logstash.conf

networks:
  kafka_kafkanet:
    external: true