version: '3.6'
services:
  squid:
    image: sameersbn/squid
    ports:
      - "3128:3128"
    volumes:
       - squid-cache:/var/spool/squid
       - squid-log:/var/log/squid
    configs:
      - source: squid_config
        target: /etc/squid/squid.conf
        uid: '0'
        gid: '0'
        mode: 0644
    secrets:
      - source: squid_tls_cert
        target: /etc/squid/ssl_cert/squid.cert
        uid: '0'
        gid: '0'
        mode: 0400
      - source: squid_tls_key
        target: /etc/squid/ssl_cert/squid.key
        uid: '0'
        gid: '0'
        mode: 0400
      - source: squid_ca_cert
        target: /etc/squid/ssl_cert/ca.crt
        uid: '0'
        gid: '0'
        mode: 0400
    deploy:
      mode: replicated
      replicas: 1

volumes:
  squid-cache:
  squid-log:

configs:
  squid_config:
    file: squid.conf

secrets:
  squid_tls_cert:
    file: squid.cert
  squid_tls_key:
    file: squid.key

networks:
  hostnet:
    external: true
    name: host


          # - target: 3130
      #   published: 3130
      #   protocol: tcp
      #   mode: host
      # - target: 3129
      #   published: 3129
      #   protocol: tcp
      #   mode: host