version: '3.6'
services:
  kafka-rest:
    image: {DOCKER_IMAGE}
    ports:
      - "${HOST_PORT:-8082}:8082"
    networks:
      kafkanet:
      schemaregistrynet:
      kafkarestnet:
        aliases:
          - kafkarest
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT:-zookeeper-01:2181}
      KAFKA_REST_LISTENERS: http://kafkarest:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schemaregistry:8081
      KAFKA_REST_HOST_NAME: kafkarest
      # KAFKA_REST_BOOTSTRAP_SERVERS: broker1:9092,broker2:9092,broker3:9092
      # KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      # KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      # KAFKA_REST_ACCESS_CONTROL_ALLOW_HEADERS: "Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Mx-ReqToken,X-Requested-With"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  kafkarestnet:
    attachable: true
  
  kafkanet:
    external: true
  
  schemaregistrynet:
    external: true