version: '3.6'
services:
  bitcoind:
    image: ${BCM_IMAGE_NAME}
    hostname: bitcoind
    volumes:
      - bitcoin_data:/data
    environment:
      BITCOIND_CHAIN: ${BCM_BITCOIN_CHAIN:-testnet}
      LXC_HOST: ${BCM_LXC_HOST:}
    networks:
      bitcoindrpcnet:
        aliases:
          - bitcoindrpc
    # secrets:
    #   - source: bitcoin_config
    #     target: /secrets/bitcoin.conf
    #     uid: '0'
    #     gid: '0'
    #     mode: 0400
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-bitcoin == true

# secrets:
#   bitcoin_config:
#     file: "build/bitcoin.conf"

volumes:
  bitcoin_data:

networks:
  bitcoindrpcnet:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24