#cloud-config
package_upgrade: true

# install host dependencies
packages:
  - zfsutils-linux
  - wait-for-it
  - tor

write_files:
  - path: /etc/lxd/preseed.yml
    content: |
      config:
        core.https_address: :8443
        core.trust_password: $BCM_LXD_SECRET
      cluster:
        server_name: $BCM_MULTIPASS_VM_NAME
        enabled: true
        cluster_address: "$BCM_LXD_CLUSTER_MASTER_IP:8443"
        cluster_certificate: "$BCM_LXD_CLUSTER_CERTIFICATE"
        server_address: "$BCM_LXD_CLUSTER_MASTER_IP"
        cluster_password: "$BCM_LXD_CLUSTER_PASSWORD"

# Initialize the LXD daemon using the provided preseed.
runcmd:
  - apt-get remove lxd lxd-client -y
  - snap install lxd --candidate
  - sh -c "(cat /etc/lxd/preseed.yml | sudo lxd init --preseed)"