name: bitcoincachemachine
version: 4.2.0
summary: LXD-based Software Defined network for home and office.
description: >
  Bitcoin Cache Machine allows you to deploy a distributed data
  to one or more computers running on your local LAN. Perfect for
  home and small office use. Add commodity hardware (x86_64) to achieve
  local high availability. Expose your services over TOR. Host and
  manage your own data.

  #TODO
# confinement: devmode

# parts:
#   geekbench4:
#     plugin: dump
#     source: http://cdn.geekbench.com/Geekbench-$SNAPCRAFT_PROJECT_VERSION-Linux.tar.gz

# apps:
#   geekbench4:
#     command: geekbench4