version: '3.4'
services:

  # TODO initialize wallet interface.
  bitcoind:
    image: farscapian/bitcoind:latest
    hostname: bitcoind
    volumes:
      - bitcoind-data:/data
      - bitcoind-log-data:/var/log/bitcoind
      - bitcoind-cookie-data:/cookie
    environment:
      BITCOIND_CHAIN: ${BCM_BITCOIN_CHAIN:-testnet}
    networks:
      bitcoindrpcnet:
        aliases:
          - bitcoindrpc
    secrets:
      - source: bitcoin_config
        target: /data/bitcoin.conf
        uid: '0'
        gid: '0'
        mode: 0400
    configs:
      - source: bitcoindtorproxy-config
        target: /etc/tor/torrc
        uid: '0'
        gid: '0'
        mode: 0644
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - engine.labels.purpose == bitcoin


secrets:
  bitcoin_config:
    file: "./bitcoind-${CHAIN:-testnet}.conf"

volumes:
  bitcoind-data:
    external: true
    
  bitcoind-log-data:
  bitcoind-cookie-data:

configs:
  bitcoindtorproxy-config:
    file: ./torrc.conf

networks:
  bitcoindrpcnet:
    attachable: true
