version: '3.7'
services:
  # Provides admin interface to lnd
  # listens on 8280
  lncli-web:
    image: <FIXME>/lncliweb:latest
    networks:
      - lnd_lndrpcnet
      - webproxynet
    volumes:
      - lnd_lnd-certificate-data:/config:ro
      - lnd_lnd-macaroon-data:/macaroons:ro
      - lnd_lnd-log-data:/logs/lnd:ro
    configs:
      - source: lncli-web_config
        target: /lncli-web/config/defaults.js
        uid: '0'
        gid: '0'
        mode: 0644
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - engine.label == bitcoin

  # an nginx proxy that is hit after reaching onionservice.
  # performs SSL termination, basic HTTP authentication, proxying to backend services
  lncliwebonionproxy:
    image: nginx:1.13.9-perl
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - webproxynet
      - onionnet
    configs:
      - source: onionproxyconf
        target: /etc/nginx/nginx.conf
        uid: '33'
        gid: '33'
        mode: 0640
    # secrets:
    #   - source: nginxbasicauth
    #     target: /run/secrets/httpusers.txt
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - engine.label == bitcoin


  # public accessibity to downstream nginx server
  onionservice:
    image: goldy/tor-hidden-service
    environment:
      LNCLIWEBONIONPROXY_PORTS: 80:80
      LNCLIWEBONIONPROXY_SERVICE_NAME: lncliwebonionproxy
    volumes:
      - onionservice-data:/var/lib/tor/hidden_service/
    networks:
      - onionnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - engine.label == bitcoin

networks:
  webproxynet:
  onionnet:
  lnd_lndrpcnet:
    external: true

volumes:
  onionservice-data:
    driver: local
  
  # anyone who needs to access lnd's gRPC or REST interface must have access to this data.
  lnd_lnd-certificate-data:
    external: true
  lnd_lnd-macaroon-data:
    external: true
  lnd_lnd-log-data:
    external: true

configs:
  onionproxyconf:
    file: "./nginx.conf"
  lncli-web_config:
    file: ./lncli-web.lncliweb.conf.js

# secrets:
#   nginxbasicauth:
#     file: ./httpusers.txt
