version: '3.6'
services:
  dnsmasq:
    image: bcm-dnsmasq:latest
    ports:
      - target: 67
        published: 67
        protocol: udp
      - target: 53
        published: 53
        protocol: udp
      - target: 53
        published: 53
        protocol: tcp
    networks: 
      hostnet: {}
      torproxynet:
    configs:
      - source: dnsmasq_config  #TODO check file permissions to least prviliege
        target: /etc/dnsmasq.conf
        uid: '33'
        gid: '33'
        mode: 0640
    deploy:
      mode: replicated
      replicas: 1

  # for outbound DNS queries on port 9053/udp.
  torproxy:
    image: bcm-tor:latest
    networks:
      torproxynet:
        aliases:
          - torproxy
    configs:
      - source: tor_config
        target: /etc/tor/torrc
        uid: '0'
        gid: '0'
        mode: 0644
    deploy:
      mode: replicated
      replicas: 1

networks:
  hostnet:
    external: true
    name: host
  torproxynet:

configs:
  dnsmasq_config:
    file: ./dnsmasq.conf
  tor_config:
    file: ./torrc