version: '3.6'
services:
  # c-lightning https://github.com/ElementsProject/lightning
  lightningd:
    image: elementsproject/lightningd
    networks:
      bitcoind_bitcoindrpcnet:
      torproxynet:
      lightningdrpcnet:
        aliases:
          - lightningdrpc
    environment:
      BITCOIND_CHAIN: ${CHAIN:-testnet}
    volumes:
      - lightningd-data:/root/.lightning
      - lightningd-log-data:/var/logs/lightningd
      - bitcoind_bitcoind-data:/etc/bitcoin
    secrets:
      - source: lightningd_conf
        target: /root/.lightning/config
        uid: '0'
        gid: '0'
        mode: 0444
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - engine.labels.purpose == bitcoin

  # tor proxy for outbound P2P services only (bitcoinrpc is exposed outside of this stack.)
  tor-proxy:
    image: osminogin/tor-simple
    networks:
      torproxynet:
        aliases:
          - torproxy
    configs:
      - source: lightningd_tor_config
        target: /etc/tor/torrc
        uid: '0'
        gid: '0'
        mode: 0644
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - engine.labels.purpose == bitcoin

configs:
  lightningd_tor_config:
    file: "./torrc"


volumes:
  lightningd-data:
  lightningd-log-data:
  bitcoind_bitcoind-data:
    external: true

networks:
  lightningdrpcnet:
    attachable: true
  bitcoind_bitcoindrpcnet:
    external: true
  torproxynet:

secrets:
  lightningd_conf:
    file: ./lightningd-${CHAIN:-testnet}.conf