#cloud-config

package_upgrade: true

# install host dependencies
packages:
  - zfsutils-linux
  - wait-for-it
  - tor

write_files:
  - path: /etc/lxd/preseed.yml
    content: |
      PRESEED

# enable lxd and remote management
runcmd:
  - cat /etc/lxd/preseed.yml | lxd init --preseed

  # - lxd init --auto --trust-password=CHANGEME --network-address=$(ip address show dev ens3 | grep "inet " |  awk '{match($0,/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/); ip = substr($0,RSTART,RLENGTH); print ip}')
  # - lxc config set core.https_address "[$(ip address show dev ens3 | grep "inet " |  awk '{match($0,/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/); ip = substr($0,RSTART,RLENGTH); print ip}')]:8443"
  # - echo "BCS_TRUSTED_HOST_INTERFACE=ens3" >> /etc/environment