version: '3.6'
services:
  rsyncd:
    image: ${BCS_INSTALL_RSYNCD_BUILD_IMAGE:-cachestack.lan/rsyncd:latest}
    #werekraken/rsync-over-ssh
      #
    ports: 
      - "2222:22"
      - "873:873"
    volumes:
      - rsync-data:/rsync
    #  - /apps/rsyncd/authorized_keys:/etc/ssh/rsync/authorized_keys:ro
    configs:
      - source: rsync_conf
        target: /etc/rsyncd.conf
        uid: '0'
        gid: '0'
        mode: 0400
    secrets:
      - source: ssh_pubkeys
        target: /etc/ssh/rsync/authorized_keys
        uid: '1000'
        gid: '1000'
        mode: 0644
    deploy:
      mode: replicated
      replicas: 1

volumes:
  rsync-data:

secrets:
  ssh_pubkeys:
    file: "./authorized_keys"

configs:
  rsync_conf:
    file: "./rsyncd.conf"