version: '3.7'
services:
  esplora:
    image: ${IMAGE_NAME}
    hostname: esplora-${CHAIN:-testnet}
    ports:
      - "${BCM_SERVICE_PORT}:5000"
    volumes:
      - esplora-data:/root/.esplora
    environment:
      CHAIN: ${CHAIN:-testnet}
      LXC_HOSTNAME: ${LXC_HOSTNAME}
    networks:
      bitcoindrpcnet:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-underlay == true

volumes:
  esplora-data:

networks:
  bitcoindrpcnet:
    external: true
    name: bitcoind-${CHAIN:-testnet}_bitcoindrpcnet
