version: 0.1
storage:
  filesystem:
    rootdirectory: /data
http:
  addr: :5000
  tls:
    certificate: /var/lib/registry/mirror.cert
    key: /var/lib/registry/mirror.key
proxy:
  remoteurl: https://registry-1.docker.io