version: 0.1
storage:
  filesystem:
    rootdirectory: /data
http:
  addr: :5000
  host: https://bcmnet:5000
  tls:
    certificate: /var/lib/registry/bcmnet.cert
    key: /var/lib/registry/bcmnet.key
proxy:
  remoteurl: https://registry-1.docker.io