version: '3.7'
services:
  lnd:
    image: ${IMAGE_NAME}
    hostname: lnd-${CHAIN:-testnet}
    #hostname required for lncl-web certificate hostname purposes (see ./lnd/start-lnd.sh)
    volumes:
      - lnd-data:/root/.lnd
      - lnd-certificate-data:/config
      - lnd-macaroon-data:/macaroons
      - lnd-log-data:/var/logs/lnd
    environment:
      LND_CERTIFICATE_HOSTNAME: lnd-${CHAIN:-testnet}  #this is so there are no certificate verification issues on lncli-web
      CHAIN: ${CHAIN:-testnet}
      HOST_ENDING: ${HOST_ENDING:-01}
    networks:
      bitcoindrpcnet:
      lndrpcnet:
        aliases:
          - lndrpc-${CHAIN}
    secrets:
      - source: lnd-config
        target: /root/.lnd/lnd.conf
        uid: '0'
        gid: '0'
        mode: 0444
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-bitcoin == true


networks:
  lndrpcnet:
    driver: overlay
    attachable: true

  bitcoindrpcnet:
    external: true
    name: bitcoind-${CHAIN:-testnet}_bitcoindrpcnet

secrets:
  lnd-config:
    file: "./lnd-${CHAIN:-testnet}.conf"

volumes:
  lnd-data:
  lnd-log-data:
  
  lnd-certificate-data:  
  lnd-macaroon-data: 