#cloud-config
package_upgrade: true

# allows for link-local name resolution from SDN controller.
packages:
 - avahi-daemon

# Add groups to the system
# The following example adds the ubuntu group with members 'root' and 'sys'
# and the empty group cloud-users.
groups:
  - lxd: [sys]

# Add users to the system. Users are added after groups are added.
users:
  - name: bcm
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: lxd
    ssh_authorized_keys:
      - $SSH_AUTHORIZED_KEY

# Run the prep script.
runcmd:
  - curl -sSL https://raw.githubusercontent.com/BitcoinCacheMachine/BitcoinCacheMachine/master/cluster/server_prep.sh | sudo bash
