#cloud-config
package_upgrade: true

# install host dependencies
packages:
  - wait-for-it
  - tor

write_files:
  - path: /entrypoint.sh
    owner: root:root
    permissions: '0500'
    content: |
      #!/bin/bash

      set -Eeuo pipefail
      cd "$(dirname "$0")"

      echo "Removing existing lxd and lxd-client using apt."

# Run the initialization script.
runcmd:
  - curl -sSL https://raw.githubusercontent.com/BitcoinCacheMachine/ServerPrep/master/prep.sh | sudo bash
#  - bash -c /entrypoint.sh