#cloud-config
package_upgrade: true

users:
  - name: ubuntu
    sudo: true
    ssh_authorized_keys:
      - $SSH_AUTHORIZED_KEY

# Run the prep script.
runcmd:
  - curl -sSL https://raw.githubusercontent.com/BitcoinCacheMachine/BitcoinCacheMachine/master/cluster/server_prep.sh | sudo bash
