version: '3.7'
services:
  bitcoind:
    image: ${DOCKER_IMAGE}
    hostname: bitcoind-${CHAIN}
    volumes:
      - bitcoin_data:/bitcoin/data
    #  - bitcoin_cookie:/bitcoin/cookie
      - bitcoin_cli:/usr/local/bin
    environment:
      CHAIN: ${CHAIN:-testnet}
      LXC_HOSTNAME: ${LXC_HOSTNAME}
      AUTH_PASSWORD_HASH: ${AUTH_PASSWORD_HASH:-}
    networks:
      bitcoindrpcnet:
        aliases:
          - bitcoindrpc-${CHAIN}
    configs:
      - source: bitcoin_config
        target: /root/.bitcoin/bitcoin.conf
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-bitcoin == true

configs:
  bitcoin_config:
    file: bitcoin.conf

volumes:
  bitcoin_data:
  #bitcoin_cookie:  
  bitcoin_cli:
 

networks:
  bitcoindrpcnet:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24