version: '3.7'
services:
  bitcoind:
    image: ${DOCKER_IMAGE}
    hostname: bitcoind-${BCM_ACTIVE_CHAIN}
    volumes:
      - bitcoin_data:/bitcoin/data
    #  - bitcoin_cookie:/bitcoin/cookie
      - bitcoin_cli:/usr/local/bin
    environment:
      BCM_ACTIVE_CHAIN: ${BCM_ACTIVE_CHAIN:-testnet}
      LXC_HOSTNAME: ${LXC_HOSTNAME}
      AUTH_PASSWORD_HASH: ${AUTH_PASSWORD_HASH:-}
      STACK_GOGO_FILE: ${STACK_GOGO_FILE:-}
      BITCOIND_CHAIN_TEXT: ${BITCOIND_CHAIN_TEXT:-}
      BITCOIND_RPC_PORT: ${BITCOIND_RPC_PORT:-}
      BITCOIND_ZMQ_BLOCK_PORT: ${BITCOIND_ZMQ_BLOCK_PORT:-}
      BITCOIND_ZMQ_TX_PORT: ${BITCOIND_ZMQ_TX_PORT:-}
    networks:
      bitcoindrpcnet:
        ipv4_address: 172.16.238.1
        aliases:
          - bitcoindrpc-${BCM_ACTIVE_CHAIN}
    configs:
      - source: bitcoin_config
        target: /root/.bitcoin/bitcoin.conf
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-bitcoin == true

configs:
  bitcoin_config:
    file: bitcoin.conf

volumes:
  bitcoin_data:
  #bitcoin_cookie:  
  bitcoin_cli:
 

networks:
  bitcoindrpcnet:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24