version: '3.7'
services:
  electrumpersonalserver:
    image: ${IMAGE_NAME}
    ports:
      - "${BCM_SERVICE_PORT}:50000"
    hostname: eps-${CHAIN:-testnet}
    volumes:
      - electrumpersonalserver-data:/root/.eps
      - bitcoin_data:/bitcoin/data
    environment:
      CHAIN: ${CHAIN:-testnet}
      HOST_ENDING: ${HOST_ENDING:-01}
    networks:
      bitcoindrpcnet:
      electrumpersonalserver:
        aliases:
          - electrumpersonalserver_${CHAIN:-testnet}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-bitcoin == true

volumes:
  electrumpersonalserver-data:

  bitcoin_data:
    external: true
    name: bitcoind-${CHAIN:-testnet}_bitcoin_data

networks:
  bitcoindrpcnet:
    external: true
    name: bitcoind-${CHAIN:-testnet}_bitcoindrpcnet

  electrumpersonalserver:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.240.0/24