version: '3.6'
services:
  dnsmasq:
    image: bcm-dnsmasq:latest
    ports:
      - target: 67
        published: 67
        protocol: udp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
    networks: 
      hostnet: {}
      torproxynet:
    configs:
      - source: dnsmasq_config
        target: /etc/dnsmasq.conf
        uid: '33'
        gid: '33'
        mode: 0640
      - source: tor_config
        target: /etc/tor/torrc
        uid: '0'
        gid: '0'
        mode: 0644
    deploy:
      mode: replicated
      replicas: 1

  # # for outbound DNS queries on port 9053/udp.
  # torproxy:
  #   image: bcm-tor:latest
  #   networks:
  #     torproxynet:
  #       aliases:
  #         - torproxy
  #   configs:
  #     - source: tor_config
  #       target: /etc/tor/torrc
  #       uid: '0'
  #       gid: '0'
  #       mode: 0644
  #   deploy:
  #     mode: replicated
  #     replicas: 1

networks:
  torproxynet:
  hostnet:
    external: true
    name: host
    
configs:
  dnsmasq_config:
    file: ./dnsmasq.conf
  tor_config:
    file: ./torrc

