version: '3.6'
services:
  schema-registry:
    image: ${DOCKER_IMAGE}
    networks:
      schemaregistrynet:
        aliases:
          - schemaregistry
      zookeepernet:
      kafkanet:
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: ${KAFKA_ZOOKEEPER_CONNECT}
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_DEBUG: "true"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-kafka == true

networks:
  kafkanet:
    external: true
    name: kafkanet

  zookeepernet:
    external: true
    name: zookeepernet

  schemaregistrynet:
    attachable: true