version: 0.1
storage:
  filesystem:
    rootdirectory: /data
http:
  addr: :5000
  host: https://$BCM_REGISTRY_HOSTNAME:5005
  # tls:
  #   certificate: /var/lib/registry/privreg.cert
  #   key: /var/lib/registry/privreg.key
