version: 0.1
storage:
  filesystem:
    rootdirectory: /data
http:
  addr: :5000
  host: https://bcmnet:443
  tls:
    certificate: /var/lib/registry/bcmnet.cert
    key: /var/lib/registry/bcmnet.key
