#cloud-config

package_upgrade: true

# install host dependencies
packages:
  - zfsutils-linux
  - wait-for-it
  - tor

# enable lxd and remote management
runcmd:
  - lxd init --auto --trust-password= --network-address=$(ip address show dev ens3 | grep "inet " |  awk '{match($0,/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/); ip = substr($0,RSTART,RLENGTH); print ip}')
  - lxc config set core.https_address "[$(ip address show dev ens3 | grep "inet " |  awk '{match($0,/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/); ip = substr($0,RSTART,RLENGTH); print ip}')]:8443"
  - echo "BCS_TRUSTED_HOST_INTERFACE=ens3" >> /etc/environment