version: '3.6'
services:

  #listens on 9021
  control-center:
    image: confluentinc/cp-enterprise-control-center
    ports:
      - "9021:9021"
    networks:
      - kafka_kafkanet
      - kafkaconnectnet
    environment:
      #CONTROL_CENTER_BOOTSTRAP_SERVERS: broker1:9092,broker2:9092,broker3:9092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper1:2181,zookeeper1:2181
      #CONTROL_CENTER_CONNECT_CLUSTER: http://kafka-connect:8083
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1s
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager