version: '3.6'
services:
  # Listens for gelf messages on TCP
  gelflistener:
    image: farscapian/logstash:latest
    ports:
      - "12201:12201/tcp"
    networks:
      kafka_kafkanet:
    configs:
      - source: logstash_config
        target: /etc/logstash.conf
        uid: '33'
        gid: '33'
        mode: 0755
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager