version: '3.6'
services:
  kafka-broker1:
    image: confluentinc/cp-kafka:4.1.1-1
    networks:
      kafka_kafkanet:
        aliases:
          - broker1
    volumes:
      - broker1-data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://broker1:9092,PLAINTEXT://broker1:9090
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == manager1
#,zookeeper2:2181,zookeeper3:2181
 
volumes:
  zoo1-data:
  zoo1-logs:
  broker1-data:

# created by zookeeper1.yml
networks:
  kafka_kafkanet:
    external: true