version: '3.4'
services:
  schema-registry:
    image: confluentinc/cp-schema-registry:4.1.1-1
    ports:
      - "8081:8081"
    networks:
      schemaregistrynet:
        aliases:
          - schemaregistry
      kafka_kafkanet:
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper1:2181,zookeeper1:2181,zookeeper1:2181
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_DEBUG: "true"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  kafka_kafkanet:
    external: true
  schemaregistrynet:
    attachable: true
  kafkarestnet:
