version: '3.6'
services:
  zoo1:
    image: zookeeper
    hostname: zoo1
    networks:
      kafkanet:
        aliases:
          - zookeeper1
    volumes:
      - zoo1-data:/var/lib/zookeeper/data
      - zoo1-logs:/var/lib/zookeeper/log
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == manager1

volumes:
  zoo1-data:
  zoo1-logs:
  broker1-data:

# overlay network that swarm hosts can use to contact kafka, if needed
networks:
  kafkanet:
    driver: overlay
    attachable: true
