version: '3.6'
services:

  # TODO initialize wallet interface.
  bitcoind:
    image: ${BCM_BITCOIN_BITCOIND_DOCKER_IMAGE}
    hostname: bitcoind
    volumes:
      - bitcoind_testnet_data:/data
      - bitcoind-log-data:/var/log/bitcoind
      - bitcoind-cookie-data:/cookie
    environment:
      BITCOIND_CHAIN: ${BCM_BITCOIN_CHAIN:-testnet}
    networks:
      bitcoindrpcnet:
        aliases:
          - bitcoindrpc
      torproxynet:
        aliases:
          - bitcoindtorproxy
    secrets:
      - source: bitcoin_config
        target: /data/bitcoin.conf
        uid: '0'
        gid: '0'
        mode: 0400
    configs:
      - source: bitcoin_tor_config
        target: /etc/tor/torrc
        uid: '0'
        gid: '0'
        mode: 0644
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - engine.labels.purpose == bitcoin

  # tor proxy for outbound P2P services only (bitcoinrpc is exposed outside of this stack.)
  tor-proxy:
    image: osminogin/tor-simple
    networks:
      torproxynet:
        aliases:
          - torproxy
    configs:
      - source: bitcoin_tor_config
        target: /etc/tor/torrc
        uid: '0'
        gid: '0'
        mode: 0644
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - engine.labels.purpose == bitcoin

secrets:
  bitcoin_config:
    file: "./bitcoind-${BCM_BITCOIN_BITCOIND_CHAIN}.conf"

configs:
  bitcoin_tor_config:
    file: "./torrc"

volumes:
  bitcoind_testnet_data:
    external: true

  bitcoind-data:
  bitcoind-log-data:
  bitcoind-cookie-data:

networks:
  bitcoindrpcnet:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
  torproxynet:
