version: '3.6'
services:

  # https://github.com/lightningnetwork/lnd
  lnd:
    image: ${BCM_BITCOIN_LND_DOCKER_IMAGE}
    #hostname required for lncl-web certificate hostname purposes (see ./lnd/start-lnd.sh)
    hostname: lnd
    networks:
      bitcoind_bitcoindrpcnet:
      lndrpcnet:
        aliases:
          - lndrpc
    environment:
      #LND_BITCOIND_REST_RPC_CREDENTIALS: "bitcoinrpcuser:qwc52LTHRa0w0UGiUr2z7fTz7JvqtxjULZ_2jaZvqmA="
      LND_CERTIFICATE_HOSTNAME: "lnd"  #this is so there are no certificate verification issues on lncli-web
      BITCOIND_CHAIN: ${CHAIN:-testnet}
    volumes:
      - lnd-data:/root/.lnd
      - lnd-certificate-data:/config
      - lnd-macaroon-data:/macaroons
      - lnd-log-data:/var/logs/lnd
    secrets:
      - source: lnd_conf
        target: /root/.lnd/lnd.conf
        uid: '0'
        gid: '0'
        mode: 0444
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - engine.labels.purpose == bitcoin

networks:
  lndrpcnet:  #connect to this if you need to communicate with lnd gRPC
    attachable: true

  bitcoind_bitcoindrpcnet:
    external: true

secrets:
  lnd_conf:
    file: "./lnd-${CHAIN:-testnet}.conf"

volumes:
  lnd-data:
  lnd-log-data:
  
  # anyone who needs to access lnd's gRPC or REST interface must have access to this data.
  lnd-certificate-data:  
  lnd-macaroon-data: 