version: '3.6'
services:
  # onion service for exposting bitcoind testnet RPC interface
  onionsite:
    image: "cachestack.lan/onionsite:latest"
    networks:
      bitcoind_bitcoindrpcnet:
    environment:
      BITCOINDRPC_PORTS: 18332:18332
      BITCOINDRPC_SERVICE_NAME: bitcoindrpc
    volumes:
      - onionservice-data:/var/lib/tor/hidden_service/
      - onionservice-logs:/logs
    configs:
      - source: onion_config
        target: /etc/tor/torrc
        uid: '0'
        gid: '0'
        mode: 0644
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - engine.labels.purpose == bitcoin

configs:
  onion_config:
    file: ./torrc


volumes:
  onionservice-data:
  onionservice-logs:
  
networks:
  onionnet:
  bitcoind_bitcoindrpcnet:
    external: true
