
version: '3.4'
services:

  bitcoinstreams:
    image: farscapian/bitcoinstreams:latest
    networks:
      kafka_kafkanet:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - engine.label == bitcoin

networks:
  kafka_kafkanet:
    external: true
