version: '3.6'
services:
  private-registry:
    image: registry:2.6.2
    ports: 
      - "80:5000"
    volumes:
      - private-registry-data:/data
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_HTTP_ADDR: :5000
    deploy:
      mode: replicated
      replicas: 1

volumes:
  private-registry-data: