version: '3.6'
services:
  # container listens on 8000
  kafka-connect-ui:
    image: landoop/kafka-connect-ui:latest
    ports:
      - "8002:8000"
    depends_on:
      - kafka-connect
    networks:
      - kafkaconnectnet
    environment:
      CONNECT_URL: http://kafkaconnect:8083
      PROXY: "true"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
