version: '3.6'
services:
  kafka-rest:
    image: confluentinc/cp-kafka-rest:4.1.1-1
    ports:
      - "8082:8082"
    networks:
      kafka_kafkanet:
      kafka_schemaregistrynet:
      kafkarestnet:
        aliases:
          - kafkarest
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper1:2181,zookeeper1:2181
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schemaregistry:8081
      KAFKA_REST_HOST_NAME: kafkarest
      # KAFKA_REST_BOOTSTRAP_SERVERS: broker1:9092,broker2:9092,broker3:9092
      # KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      # KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      # KAFKA_REST_ACCESS_CONTROL_ALLOW_HEADERS: "Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Mx-ReqToken,X-Requested-With"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  kafkarestnet:
    attachable: true
  kafka_kafkanet:
    external: true
  kafka_schemaregistrynet:
    external: true