version: '3.7'
services:
  electrs:
    image: ${IMAGE_NAME}
    ports:
      - "50001:50001"
    hostname: electrs-${CHAIN:-testnet}
    volumes:
      - electrs-data:/root/.electrs
      - bitcoin-data:/root/.bitcoin:ro
    environment:
      CHAIN: ${CHAIN:-testnet}
      HOST_ENDING: ${HOST_ENDING:-01}
    networks:
      bitcoindrpcnet:
      electrsnet:
        aliases:
          - electrsnet_${CHAIN:-testnet}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-bitcoin == true

volumes:
  electrs-data:

  bitcoin-data:
    external: true
    name: bitcoind-${CHAIN:-testnet}_bitcoin_data

networks:
  bitcoindrpcnet:
    external: true
    name: bitcoind-${CHAIN:-testnet}_bitcoindrpcnet

  electrsnet:
    driver: overlay
    attachable: true
