version: '3.6'
services:
  squid:
    image: bcm-squid:latest
    ports:
      - target: 3128
        published: 3128
        protocol: tcp
        mode: host
    networks:
      hostnet: {}
    volumes:
       - squid-cache:/var/spool/squid
       - squid-log:/var/log/squid
    configs:
      - source: squid_config
        target: /etc/squid/squid.conf
        uid: '0'
        gid: '0'
        mode: 0644
    deploy:
      mode: replicated
      replicas: 1

volumes:
  squid-cache:
  squid-log:

configs:
  squid_config:
    file: squid.conf

networks:
  hostnet:
    external: true
    name: host