version: '3.7'
services:
  rtl:
    image: ${IMAGE_NAME}
    hostname: rtl-${BCM_ACTIVE_CHAIN:-testnet}
    ports:
      - "${SERVICE_PORT:-}:${SERVICE_PORT:-}"
    volumes:
      - lnd-macaroons:/lnd-macaroons
      - bitcoind-data:/root/.bitcoin
      - lnd-data:/root/.lnd
    environment:
      PORT: ${SERVICE_PORT:-}
      MACAROON_PATH: ${MACAROON_PATH:-}
      NODE_AUTH_TYPE: CUSTOM
      LND_CONFIG_PATH: /root/.lnd/lnd-rtl.conf
      RTL_CONFIG_PATH: /root/.rtl/RTL.conf
      BITCOIND_CONFIG_PATH: /root/.bitcoin/bitcoind-rtl.conf
      RTL_SSO: 0
      RTL_COOKIE_PATH: /root/.rtl/cookie
      LOGOUT_REDIRECT_LINK: http://bcm
      RTL_PASS: ${RTL_PASSWORD:-}
      LND_SERVER_URL: https://lndrpc-${BCM_ACTIVE_CHAIN}:8080/v1
    networks:
      lndrpcnet:    
    secrets:
      - source: rtl-config
        target: /root/.rtl/RTL.conf
        uid: '0'
        gid: '0'
        mode: 0444
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-bitcoin == true

networks:
  lndrpcnet:
    external: true
    name: lnd-${BCM_ACTIVE_CHAIN:-}_lndrpcnet
  
secrets:
  rtl-config:
    file: rtl.conf

volumes:
  lnd-macaroons:
    external: true
    name: lnd-${BCM_ACTIVE_CHAIN:-}_lnd-macaroon-data

  lnd-data:
    external: true
    name: lnd-${BCM_ACTIVE_CHAIN:-}_lnd-data

  bitcoind-data:
    external: true
    name: bitcoind-${BCM_ACTIVE_CHAIN:-}_bitcoin_data

