#cloud-config
package_upgrade: true

# install host dependencies
packages:
  - zfsutils-linux
  - wait-for-it
  - tor

# Initialize the LXD daemon using the provided preseed.
runcmd:
  - apt-get remove lxd lxd-client -y
  - snap install lxd --candidate
