version: '3.7'
services:
  # https://github.com/ElementsProject/lightning-charge
  # image listens on TCP 9112
  lightning-charge:
    image: ${BCM_INSTALL_BITCOIN_LIGHTNING_CHARGE_DOCKER_IMAGE}
    networks:
      lightningd_lightningdrpcnet:
      lightning-chargenet:
        aliases:
          lightningchargerpc
    volumes:
      - lightning-charge-data:/data
      - lightningd-data:/etc/lightning
      - bitcoind-testnet-data:/etc/bitcoin
    environment:
      API_TOKEN: mySecretToken
      LN_PATH: /etc/lightning
      BITCOIND_URI: http://user:changeme@bitcoindrpc:18332
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - engine.labels.purpose == bitcoin

volumes:
  lightning-charge-data:
  lightningd-data:
    external: true
  bitcoind-testnet-data:
    external: true

networks:
  lightningd_lightningdrpcnet:
    external: true
  lightning-chargenet:  #for components needing to talk to the lightning-charge API.
    attachable: true
