version: '3.6'
services:
  schema-registry-ui:
    image: landoop/schema-registry-ui:latest
    ports:
      - "8000:8000"
    networks:
      - kafka_schemaregistrynet
    environment:
      SCHEMAREGISTRY_URL: http://schemaregistry:8081
      PROXY: "true"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  kafka_schemaregistrynet:
    external: true