version: '3.6'
services:
  clightning:
    image: ${IMAGE_NAME}
    hostname: clightning-${CHAIN:-testnet}
    volumes:
      - clightning-data:/root/.lightning
      - clightning-log-data:/var/log/clightning
      - bitcoin_data:/data/bitcoin
    environment:
      CHAIN: ${CHAIN:-testnet}
      HOST_ENDING: ${HOST_ENDING:-01}
    networks:
      bitcoindrpcnet:
      clightningrpcnet:
        aliases:
          - clightningrpc
    secrets:
      - source: clightning_conf
        target: /root/.lightning/config
        uid: '0'
        gid: '0'
        mode: 0444
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-bitcoin == true

volumes:
  clightning-data:
  clightning-log-data:

  bitcoin_data:
    external: true
    name: bitcoind-${CHAIN:-testnet}_bitcoin_data

networks:
  clightningrpcnet:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24

  bitcoindrpcnet:
    external: true
    name: bitcoind-${CHAIN:-testnet}_bitcoindrpcnet
  
secrets:
  clightning_conf:
    file: clightning.conf