version: '3.7'
services:
  clightning:
    image: ${IMAGE_NAME}
    hostname: clightning-${BCM_ACTIVE_CHAIN:-}
    volumes:
      - clightning-data:/root/.lightning
      - clightning-log-data:/var/log/clightning
      - bitcoin_data:/bitcoin/data
      - bitcoin_cli:/usr/local/bin
    environment:
      LXC_HOSTNAME: ${LXC_HOSTNAME}
      BITCOIND_RPC_PORT: ${BITCOIND_RPC_PORT:-}
      BCM_ACTIVE_CHAIN: ${BCM_ACTIVE_CHAIN:-}
      CHAIN_TEXT: ${CHAIN_TEXT:-}
    networks:
      bitcoindrpcnet:
      clightningrpcnet:
        aliases:
          - clightningrpc-${BCM_ACTIVE_CHAIN}
    secrets:
      - source: clightning_conf
        target: /root/.lightning/config
        uid: '0'
        gid: '0'
        mode: 0444
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-bitcoin == true

volumes:
  clightning-data:
  clightning-log-data:

  bitcoin_data:
    external: true
    name: bitcoind-${BCM_ACTIVE_CHAIN:-}_bitcoin_data

  bitcoin_cli:
    external: true
    name: bitcoind-${BCM_ACTIVE_CHAIN:-}_bitcoin_cli

networks:
  clightningrpcnet:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24

  bitcoindrpcnet:
    external: true
    name: bitcoind-${BCM_ACTIVE_CHAIN:-}_bitcoindrpcnet
  
secrets:
  clightning_conf:
    file: clightning.conf